server:
  port: 3333
  
spring:
  datasource:
    url: ${JDBC_URL}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
    driver-class-name: oracle.jdbc.driver.OracleDriver
  application:
    name: maps-service
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: validate

info:
  app:
    name: Rideshare Map Service
    description: This is the map service for the Rideshare Map.

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka